-- SHOW TIMEZONE
-- SELECT NOW()
-- SELECT TIMEOFDAY()
-- SELECT CURRENT_TIME
-- SELECT CURRENT_DATE
-- SELECT EXTRACT(DAY FROM Payment_date) AS Payment_year,Payment_date FROM payments;
-- SELECT EXTRACT(WEEK FROM Payment_date) AS Payment_year,Payment_date FROM payments;
-- SELECT EXTRACT(MONTH FROM Payment_date) AS Payment_year,Payment_date FROM payments;
-- SELECT EXTRACT(QUARTER FROM Payment_date) AS Payment_year,Payment_date FROM payments;
-- SELECT EXTRACT(YEAR FROM Payment_date) AS Payment_year,Payment_date FROM payments;
-- SELECT EXTRACT(DOW FROM Payment_date) AS Payment_year,Payment_date FROM payments;
-- SELECT EXTRACT(DOY FROM Payment_date) AS Payment_year,Payment_date FROM payments;